directory: ~/music
import:
    move: yes
match:
    preferred:
        countries: [GB|UK, XE, XW, US]
        media: [CD, Digital Media|File]
plugins: duplicates fetchart embedart lastgenre lastimport missing info mpdstats mpdupdate web # smartplaylist
lastfm:
    user: parnmatt
smartplaylist:
    relative_to: ~/music
    playlist_dir: ~/.config/mpd/playlists
    playlists:
        - name: all.m3u
          query: ''
        - name: alterbridge.m3u
          query: 'artist:"Alter Bridge"'
